title: Abdul Hafiz Bin Suib       # Title of the site
logo: profile.png      # Profile photo (placed in an "img" folder)
show_download: true                # Adds a "Download" button for the repo
theme: jekyll-theme-minimal        # Theme style
